import {StyleSheet} from "react-native";

export const styles = StyleSheet.create({
    wrapper: {
        width: "100%",
        height: "100%",
        backgroundColor: "white",
    },
    wrapper__btn_show: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        width: 342,
        height: 36,
        backgroundColor: 'white',
        marginTop: 48,
        marginBottom: 44,
        marginLeft: "auto",
        marginRight: "auto",
        borderWidth: 2,
        borderRadius: 8,
        borderColor: "rgba(47, 130, 201, 1)",
    },
    wrapper__btn_add: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        width: 342,
        height: 55,
        backgroundColor: "rgba(47, 130, 201, 1)",
        marginTop: 48,
        marginBottom: 44,
        marginLeft: "auto",
        marginRight: "auto",
        borderWidth: 2,
        borderRadius: 8,
        borderColor: "rgba(47, 130, 201, 1)",
    },
    wrapper__list: {
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "column",
        width: 342,
        marginLeft: "auto",
        marginRight: "auto",
    },
    wrapper__list__item: {
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
        flexDirection: "row",
        width: 342,
        borderTopColor: `#EEF8FD`,
        borderTopWidth: 1,
        padding: 8,
    },
    wrapper__list__item__checkbox: {
        width: 30,
        height: 30,
        borderRadius: 8,
        borderWidth: 2,
        textAlign: "center",
        textAlignVertical: "center"
    },
    wrapper__list__item__checkbox_select: {
        width: 30,
        height: 30,
        borderRadius: 8,
        backgroundColor: `rgba(43, 158, 72, 1)`,
        color: "white",
        textAlign: "center",
        textAlignVertical: "center",
        display: "flex",
        alignItems: "center",
        justifyContent: "center"
    },
    wrapper__list__item__delete: {
        width: 40,
        height: 40,
        backgroundColor: "#F8F8F8",
        borderRadius: 8,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        cursor: "pointer",
    },
    wrapper__list__item__delete__img: {
        width: 30,
        height: 30,
    },
    wrapper__list__item__content: {
        width: 230,
        padding: 8,
    },
    wrapper__list__item__title: {
        fontSize: 17,
        fontWeight: "bold",
    },
    wrapper__list__item__text: {},
    wrapper__list__item__text_complete: {},
})